export const PACKAGE_ID = "0x5bad0e68cd4d4a459cf5c4693536ea9d041ba9d8f1844001dcd1334e9a06659f"
export const NET_ENV = "testnet"

export const initialBase64 = "oRzrCwYAAAAKAQAMAgwSAx4hBD8GBUVGB4sBmgEIpQKAAQalA6QBCskEBQzOBEAADQEKAgQCDwIQAw4AAQIAAQAHAQAAAwICAAQDBwAABwABAAEJAQQBAAEMBgQBAAIGBwgABAgFAwAFCwoBAQIBAwIDBQkCCAAHCAIABQsBAQgDCgILAQEIAwgACwEBCAMBCAMBCwEBCQABCgIBCQABBgoCAQUBCAAICQACCgIKAgoCCwEBCAMFBwgCBk9wdGlvbghURU1QTEFURQlUeENvbnRleHQDVXJsB2FkZHJlc3MLZHVtbXlfZmllbGQQZnJvbV9hc2NpaV9ieXRlcwRpbml0FW5ld191bnNhZmVfZnJvbV9ieXRlcwRub25lBm9wdGlvbghyZWdpc3RlcgRzb21lCHRlbXBsYXRlCXRva2VuaXplZAp0eF9jb250ZXh0A3VybAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlutDmjNTUpFnPXEaTU26p0EG6nY8YRAAdzRM06aBmWfCgIBAAMIAEB6EPNaAAACAQYKAhkYV3JhcHBlciBUb2tlbml6ZWQgU3ltYm9sCgIXFldyYXBwZXIgVG9rZW5pemVkIE5hbWUKAh4dV3JhcHBlciBUb2tlbml6ZWQgRGVzY3JpcHRpb24KAjk4aHR0cHM6Ly90aC5iaW5nLmNvbS90aC9pZC9PSVAuS0liUVZXOTk1c2RvbVA3aEF1c2hRZ0hhSGEAAgEFAQAAAAACHgcGBwAhBAc4AAwCBQsHBhEEOAEMAgsCDAYLAAwFCwYMBAcADAMLBQcCBwMHBAcFCwQOAxEDCwE4AgIA";
export const module_prefix = "T_";
export const constants_alias = [
    { name: "constant_0", alias: "LOCKED_OBJECT" },
    { name: "constant_1", alias: "TOTAL_SUPPLY" },
    { name: "constant_2", alias: "DECIMALS" },
    { name: "constant_3", alias: "SYMBOL" },
    { name: "constant_4", alias: "NAME" },
    { name: "constant_5", alias: "DESCRIPTION" },
    { name: "constant_6", alias: "ICON_URL" },
];

